/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,mdx}"],
  theme: {
    extend: {
      // ── Login page (login_ebspl_2) Material Design 3 palette ──
      colors: {
        "surface-container-highest": "#d9e4e9",
        "surface-tint": "#644eaf",
        error: "#ba1a1a",
        background: "#f1fbff",
        surface: "#f1fbff",
        "primary-fixed-dim": "#ccbdff",
        "tertiary-fixed": "#6dfad2",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-variant": "#d9e4e9",
        "secondary-container": "#6f5fea",
        "on-primary-fixed-variant": "#4c3595",
        "on-primary-container": "#b09aff",
        "on-surface-variant": "#484551",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#19bf9a",
        "on-surface": "#131d21",
        "on-secondary-fixed": "#160066",
        "inverse-on-surface": "#e7f3f7",
        secondary: "#5644d0",
        "on-primary-fixed": "#1f005f",
        "on-background": "#131d21",
        "surface-container-high": "#dfeaef",
        primary: "rgb(var(--ebspl-primary) / <alpha-value>)",
        "primary-dark": "rgb(var(--ebspl-primary-dark) / <alpha-value>)",
        "secondary-fixed-dim": "#c6bfff",
        "primary-fixed": "#e7deff",
        tertiary: "#002f24",
        "surface-container": "#e4f0f4",
        "on-tertiary-fixed": "#002018",
        "primary-container": "#432b8c",
        "on-secondary-fixed-variant": "#4029ba",
        "inverse-surface": "#283236",
        "surface-dim": "#d1dce0",
        "tertiary-fixed-dim": "#4bddb7",
        "outline-variant": "#cac4d3",
        "tertiary-container": "#004738",
        outline: "#797583",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "inverse-primary": "#ccbdff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eaf5fa",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005140",
        "surface-bright": "#f1fbff",
        "secondary-fixed": "#e4dfff",
        "on-secondary-container": "#fffbff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "container-padding": "24px",
        "stack-lg": "24px",
        unit: "4px",
        "stack-md": "16px",
        gutter: "16px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "title-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "data-mono": ["Inter"],
        "label-bold": ["Inter"],
        "display-lg": ["Manrope"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
